name: generate

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */3 * * *' # Run every three hours

jobs:
  schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.5
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: make gen
